# the BioSample accession
biosample_accession: SAMN17836431

# name of CSV file listing barcode runs to uploade
barcode_runs: ../data/barcode_runs.csv

# the following come from the SRA FTP upload instructions
ftp_username: subftp
ftp_account_folder: uploads/jbloom_fhcrc.org_IuMBgK44

# Meaningful name for this sample's FTP folder:
ftp_subfolder: LY-CoV555_antibody_barcodes
